steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/transportadora/transportadora-saas:$BUILD_ID
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/transportadora/transportadora-saas:$BUILD_ID

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - transportadora
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/transportadora/transportadora-saas:$BUILD_ID
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8080"
      - --cpu
      - "1"
      - --memory
      - 512Mi
      - --min-instances
      - "0"
      - --max-instances
      - "5"
      - --concurrency
      - "80"
      - --set-env-vars
      - NODE_ENV=production,APP_UPDATE_STORAGE_BUCKET=transportadora-ota-754837345818
      - --set-secrets
      - JWT_SECRET=jwt-secret:latest,REFRESH_TOKEN_SECRET=refresh-token-secret:latest,DATABASE_URL=database-url:latest,FIREBASE_SERVICE_ACCOUNT_JSON=firebase-service-account-json:latest,APP_UPDATE_SIGNING_PRIVATE_KEY_PEM=app-update-signing-private-key-pem:latest

substitutions:
  _REGION: us-central1

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/transportadora/transportadora-saas:$BUILD_ID
