import Database from 'better-sqlite3';
import { Pool } from 'pg';
import * as path from 'path';

const SQLITE_DB_PATH = process.env.SQLITE_DB_PATH || path.join(__dirname, '../transportadora.db');
const DATABASE_URL = process.env.DATABASE_URL;

if (!DATABASE_URL) {
  console.error('DATABASE_URL es requerido para migrar a PostgreSQL/Supabase.');
  process.exit(1);
}

const sqlite = new Database(SQLITE_DB_PATH);
const pg = new Pool({ connectionString: DATABASE_URL, max: 5 });

type ColumnInfo = {
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
};

function q(identifier: string) {
  return `"${identifier.replace(/"/g, '""')}"`;
}

function pgType(sqliteType: string) {
  const type = sqliteType.toUpperCase();
  if (type.includes('INT')) return 'INTEGER';
  if (type.includes('REAL') || type.includes('FLOA') || type.includes('DOUB')) return 'DOUBLE PRECISION';
  if (type.includes('BLOB')) return 'BYTEA';
  return 'TEXT';
}

function pgDefault(value: string | null) {
  if (!value) return '';
  if (/CURRENT_TIMESTAMP/i.test(value)) return ' DEFAULT CURRENT_TIMESTAMP';
  if (/^'.*'$/.test(value) || /^-?\d+(\.\d+)?$/.test(value)) return ` DEFAULT ${value}`;
  return '';
}

function columnDefinition(column: ColumnInfo, inlinePrimaryKey: boolean) {
  if (inlinePrimaryKey && column.pk) {
    const type = pgType(column.type);
    if (type === 'INTEGER' && column.name === 'id') {
      return `${q(column.name)} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
    }
    return `${q(column.name)} ${type} PRIMARY KEY`;
  }
  const nullable = column.notnull ? ' NOT NULL' : '';
  return `${q(column.name)} ${pgType(column.type)}${pgDefault(column.dflt_value)}${nullable}`;
}

async function createTable(table: string, columns: ColumnInfo[]) {
  const primaryColumns = columns.filter(column => column.pk).sort((a, b) => a.pk - b.pk);
  const inlinePrimaryKey = primaryColumns.length === 1;
  const definitionsList = columns.map(column => columnDefinition(column, inlinePrimaryKey));
  if (primaryColumns.length > 1) {
    definitionsList.push(`PRIMARY KEY (${primaryColumns.map(column => q(column.name)).join(', ')})`);
  }
  const definitions = definitionsList.join(', ');
  await pg.query(`CREATE TABLE IF NOT EXISTS ${q(table)} (${definitions})`);
}

async function migrateTable(table: string) {
  const columns = sqlite.prepare(`PRAGMA table_info(${q(table)})`).all() as ColumnInfo[];
  if (columns.length === 0) return { table, rows: 0 };

  await createTable(table, columns);

  const columnNames = columns.map(column => column.name);
  const rows = sqlite.prepare(`SELECT ${columnNames.map(q).join(', ')} FROM ${q(table)}`).all() as Record<string, any>[];
  if (rows.length === 0) return { table, rows: 0 };

  const placeholders = columnNames.map((_, index) => `$${index + 1}`).join(', ');
  const insertSql = `
    INSERT INTO ${q(table)} (${columnNames.map(q).join(', ')})
    VALUES (${placeholders})
    ON CONFLICT DO NOTHING
  `;

  const client = await pg.connect();
  try {
    await client.query('BEGIN');
    for (const row of rows) {
      await client.query(insertSql, columnNames.map(column => row[column]));
    }
    const idColumn = columns.find(column => column.pk && column.name === 'id');
    if (idColumn) {
      await client.query(`
        SELECT setval(pg_get_serial_sequence($1, 'id'), COALESCE((SELECT MAX(id) FROM ${q(table)}), 1), true)
      `, [table]);
    }
    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }

  return { table, rows: rows.length };
}

async function main() {
  const tables = sqlite
    .prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    .all() as { name: string }[];

  console.log(`Migrando ${tables.length} tablas desde ${SQLITE_DB_PATH}`);
  await pg.query('SELECT NOW()');

  if (process.env.RESET_POSTGRES_TABLES === 'true') {
    console.log('Reiniciando tablas destino en PostgreSQL...');
    for (const { name } of [...tables].reverse()) {
      await pg.query(`DROP TABLE IF EXISTS ${q(name)} CASCADE`);
    }
  }

  let totalRows = 0;
  for (const { name } of tables) {
    const result = await migrateTable(name);
    totalRows += result.rows;
    console.log(`${result.table}: ${result.rows} filas`);
  }

  console.log(`Migracion finalizada. Filas copiadas: ${totalRows}`);
}

main()
  .catch(error => {
    console.error('Error migrando a PostgreSQL:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    sqlite.close();
    await pg.end();
  });
